Bugfix for handling 0 byte modification in diff view
I encountered an exception being thrown when viewing diff of two archives.

The exception was
'''
vorta/views/diff_result.py", line 52, in parse_line
    size = int(size)
ValueError: invalid literal for int() with base 10: ''
'''

which was caused by diff line:

'''
0 B   -2.6 kB home/philroche/.config/google-chrome/Profile 1/QuotaManager-journal
'''

This commit fixes the issue by only stripping +/- from string if they exist.